### ISSUE TITLE
Dots don't matter in Gmail addresses

### ISSUE THREAD

**Issue by laurivosandi** [passmower/passmower#57]
This should be at least enabled for gmail.com addresses, possibly make it configurable: All domains, no domains or list of domains supplied by env var. Wildduck also by the way ignores dots

https://support.google.com/mail/answer/7436150?hl=en

**Comment by veebkolm** [comment]
[Supported addresses](https://github.com/validatorjs/validator.js?tab=readme-ov-file#sanitizers) are now normalized with validator.js if `NORMALIZE_EMAIL_ADDRESSES` is set to true.
